Update setup and running instructions
DUNE-DAQ/justintime pull request #26
Opened 2024-04-01 15:33 UTC by andrewmogan

The current README is essentially a list of commands with little context or explanation. There's also no explanation of ssh tunneling, which may not be obvious to everyone. These README updates attempt to clarify these points.

2024-04-04 18:53 UTC, alessandrothea requested changes, later dismissed

2024-04-04 18:53 UTC, alessandrothea commented on README.md
> +source env.sh
This is needed for running just in time, not for the setup.
Remove

2024-04-04 18:53 UTC, alessandrothea commented on README.md
> +source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
Tis is a repeat of basic daq area instructions and should be avoided. 
A link to basic setup instructions should be used instead.

2024-04-04 18:53 UTC, alessandrothea commented on README.md
> +To run `justintime`, you need a directory containing HDF5-format DUNE DAQ data files and you need to select a channel map. As of March 2024, the available channel map options are 'VDColdbox', 'ProtoD
Why did you remove the environment setup commands?

2025-03-11 16:36 UTC, wesketchum approved these changes

2025-03-11 16:37 UTC, merged